@php
$imagePath = public_path('pdf-cover.png');
$imageData = file_exists($imagePath) ? base64_encode(file_get_contents($imagePath)) : '';
@endphp

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Gratitude Stories Export</title>
    <style>
        @page {
            size: A4;
            margin: 0;
        }

        html,
        body {
            margin: 0;
            padding: 0;
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 12px;
            line-height: 1.6;
            color: #333;
        }

        .cover-page {
            width: 100%;
            height: 100vh;
            position: relative;
            page-break-after: always;
        }

        .cover-image {
            width: 100%;
            height: 100%;
            object-fit: cover;
            display: block;
        }

        .content-pages {
            padding: 40px;
        }

        .cover-title {
            font-size: 36px;
            font-weight: bold;
            color: #902042;
            margin-bottom: 20px;
            border-bottom: 3px solid #902042;
            padding-bottom: 15px;
        }

        .cover-subtitle {
            font-size: 18px;
            color: #7f8c8d;
            margin-bottom: 40px;
        }

        .cover-stats {
            background: #f8f9fa;
            padding: 30px;
            border-radius: 8px;
            margin: 40px 0;
            border-left: 4px solid #902042;
        }

        .cover-stats h3 {
            font-size: 16px;
            margin-bottom: 15px;
            color: #902042;
        }

        .stat-item {
            margin: 8px 0;
            font-size: 14px;
        }

        .cover-footer {
            margin-top: 60px;
            font-size: 14px;
            color: #95a5a6;
        }

        .story {
            margin-bottom: 50px;
            padding: 25px;
            border: 1px solid #e9ecef;
            border-radius: 8px;
            background: #ffffff;
            page-break-inside: avoid;
        }

        .story-header {
            margin-bottom: 20px;
            padding-bottom: 15px;
            border-bottom: 2px solid #f1f2f6;
        }

        .story-title {
            font-size: 18px;
            font-weight: bold;
            color: #902042;
            margin-bottom: 8px;
        }

        .story-meta {
            font-size: 11px;
            color: #7f8c8d;
            margin-bottom: 15px;
        }

        .story-prompt {
            background: #f8f9fa;
            padding: 15px;
            border-left: 4px solid #902042;
            margin-bottom: 20px;
            border-radius: 4px;
        }

        .story-prompt-label {
            font-weight: bold;
            font-size: 11px;
            color: #902042;
            text-transform: uppercase;
            margin-bottom: 8px;
        }

        .story-prompt-text {
            font-style: italic;
            color: #555;
        }

        .story-content {
            margin-bottom: 20px;
            line-height: 1.7;
            text-align: justify;
        }

        .story-author {
            text-align: right;
            font-size: 11px;
            color: #7f8c8d;
            font-style: italic;
            margin-top: 15px;
            padding-top: 15px;
            border-top: 1px solid #ecf0f1;
        }

        .word-count {
            font-size: 10px;
            color: #95a5a6;
            margin-left: 10px;
        }
    </style>
</head>

<body>

    @if($imageData)
    <div class="cover-page">
        <img src="data:image/png;base64,{{ $imageData }}" alt="Cover Image" class="cover-image" />
    </div>
    @endif

    <div class="content-pages">
        <!-- Title Section -->
        <div style="page-break-after: always; text-align: center;">
            <h1 class="cover-title">Gratitude Stories</h1>
            <p class="cover-subtitle">Complete Collection of User Stories</p>

            <div class="cover-stats">
                <h3>Export Summary</h3>
                <div class="stat-item"><strong>Total Users:</strong> {{ $totalUsers }}</div>
                <div class="stat-item"><strong>Total Stories:</strong> {{ $totalStories }}</div>
                <div class="stat-item"><strong>Generated:</strong> {{ $generatedAt->format('F d, Y \a\t H:i') }}</div>
            </div>

            <div class="cover-footer">
                <p>This document contains all gratitude stories generated by users.</p>
                <p>Each story reflects personal moments of gratitude and thankfulness.</p>
            </div>
        </div>

        <!-- User Stories -->
        @foreach($usersWithStories as $user)
        @foreach($user->gratitudeStories as $story)
        <div class="story">
            <div class="story-header">
                <div class="story-title">
                    {{ $story->title }}
                    <span class="word-count">({{ str_word_count(strip_tags($story->generated_story)) }} words)</span>
                </div>
                <div class="story-meta">
                    Created on {{ $story->created_at->format('F d, Y \a\t H:i') }}
                </div>
            </div>

            @if($story->user_prompt)
            <div class="story-prompt">
                <div class="story-prompt-label">User Prompt</div>
                <div class="story-prompt-text">{{ $story->user_prompt }}</div>
            </div>
            @endif

            <div class="story-content">
                {!! nl2br(e($story->generated_story)) !!}
            </div>

            <div class="story-author">
                — Author: {{ $user->name }}
            </div>
        </div>
        @endforeach
        @endforeach

        <!-- Legacy Stories -->
        @foreach($storiesWithoutUser as $story)
        <div class="story">
            <div class="story-header">
                <div class="story-title">
                    {{ $story->title }}
                    <span class="word-count">({{ str_word_count(strip_tags($story->generated_story)) }} words)</span>
                </div>
                <div class="story-meta">
                    Created on {{ $story->created_at->format('F d, Y \a\t H:i') }}
                </div>
            </div>

            @if($story->user_prompt)
            <div class="story-prompt">
                <div class="story-prompt-label">User Prompt</div>
                <div class="story-prompt-text">{{ $story->user_prompt }}</div>
            </div>
            @endif

            <div class="story-content">
                {!! nl2br(e($story->generated_story)) !!}
            </div>

            <div class="story-author">
                — Author: Anonymous User
            </div>
        </div>
        @endforeach
    </div>

</body>

</html>